name: ticket_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Local Assets
  assets:
    - assets/icons/
    - assets/images/

  # Local Fonts
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: CustomIcons
      fonts: 
        - asset: assets/icons/CustomIcons.ttf
